name: gh-deploy


on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install requests_oauthlib
      - run: pip install click
      - run: pip install click-plugins
      - run: pip install click-config-file
      - run: pip install pytest
      - run: pip install mkdocs
      - run: pip install mkdocstrings
      - run: pip install mkdocs-click
      - run: pip install pygments
      - run: pip install pymdown-extensions
      - run: pip install mkdocs-autolinks-plugin
      - run: pip install mkdocs-jupyter
      - run: pip install mkdocs-exclude
      - run: pip install mkdocs-exclude-search
      - run: pip install mkdocs-macros-plugin
      - run: pip install mkdocs-print-site-plugin
      - run: pip install mkdocs-pdf-export-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-windmill
      - run: pip install mkdocs-img2fig-plugin
      - run: pip install mkdocs-rss-plugin
      - run: mkdocs gh-deploy --force
